---
- name: Create monitoring directory
  file:
    path: /root/monitoring
    state: directory
    mode: '0755'

- name: Copy docker-compose
  copy:
    src: docker-compose.yml
    dest: /root/monitoring/docker-compose.yml

- name: Copy loki config
  copy:
    src: loki-config.yml
    dest: /root/monitoring/loki-config.yml

- name: Copy promtail config
  copy:
    src: promtail-config.yml
    dest: /root/monitoring/promtail-config.yml

- name: Copy prometheus config
  copy:
    src: prometheus/prometheus-config.yml
    dest: /root/monitoring/prometheus/prometheus-config.yml

- name: Copy prometheus config
  copy:
    src: prometheus/rules.yml
    dest: /root/monitoring/prometheus/rules.yml

- name: Copy alertmanager config
  copy:
    src: alertmanager/alertmanager.yml
    dest: /root/monitoring/alertmanager/alertmanager.yml

- name: Copy grafana provisioning
  copy:
    src: grafana/
    dest: /root/monitoring/grafana/

- name: Start monitoring containers
  community.docker.docker_compose_v2:
    project_src: /root/monitoring
    files:
      - docker-copmose.yml
    state: present
    pull: always
