FROM node:24.14-alpine AS builder
ENV NODE_ENV=prodution
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --only=prodution
COPY . .
RUN npm run build


FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


