FROM node:24.14-alpine

ENV DATABASE_URL=${DATABASE_URL}
ENV PORT=${PORT}

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --omit=dev

COPY ./src ./src

EXPOSE 5000

CMD ["npm", "start"]

HEALTHCHECK --interval=10s --timeout=3s --retries=5s \
CMD curl -f http://localhost:5000/health || exit 1
