FROM node:20.19-alpine

ENV DATABASE_URL=${DATABASE_URL}
ENV PORT=${PORT}

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --only=production

COPY ./src ./src

EXPOSE 4450

CMD ["npm", "start"]
