apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: {{ .Values.namespace }}
data:
  alertmanager.yml: |
{{ tpl (.Files.Get "files/alertmanager/alertmanager.yml") .| indent 4 }}
