apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.namespace }}
data:
  datasource.yml: |
{{ .Files.Get "files/grafana/datasources/datasource.yml" | indent 4 }}
