---
- name: Login to GHCR
  community.docker.docker_login:
    registry: ghcr.io
    username: "{{ghcr_username}}"
    password: "{{ghcr_password}}"

- name: Create project directory
  file:
    path: /root/app
    state: directory
    mode: '0755'

- name: Copy docker-compose
  copy:
    src: docker-compose.prod.yml
    dest: /root/app/docker-compose.prod.yml

- name: Copy nginx.conf
  copy:
    src: nginx.conf
    dest: /root/app/nginx.conf

- name: Copy .env
  copy:
    src: .env
    dest: /root/app/.env
    mode: '0600'

- name: Run Node Exporter on app server
  community.docker.docker_container:
    name: node-exporter
    image: prom/node-exporter:latest
    restart_policy: unless-stopped
    pid_mode: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
  become: true

- name: Run cAdvisor on app server
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart_policy: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  become: true

- name: Start containers
  community.docker.docker_compose_v2:
    project_src: /root/app
    files:
      - docker-compose.prod.yml
    state: present
    pull: always
