global:
  resolve_timeout: 5m
  smtp_smarthost: '{{ .Values.alertmanager.smtpHost }}'
  smtp_from: '{{ .Values.alertmanager.smtpFrom }}'
  smtp_auth_username: '{{ .Values.alertmanager.smtpUser }}'
  smtp_auth_password: '{{ .Values.alertmanager.smtpPassword }}'
  smtp_require_tls: true

route:
  receiver: "default"
  group_by: ["alertname", "instance"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

  routes:
    - match:
        severity: page
      receiver: page

    - match:
        severity: warning
      receiver: warning

    - match:
        severity: critical
      receiver: critical

receivers:
  - name: "default"
    webhook_configs:
      - url: "http://localhost:5001/alerts"
    email_configs:
    - to: '{{ .Values.alertmanager.smtpTo }}'
      send_resolved: true
  - name: page
  - name: warning
  - name: critical
