---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-v2
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: true
