"all":
  "hosts":
    "app":
      "ansible_host": "139.100.219.183"
      "ansible_ssh_private_key_file": "~/.ssh/id_ed25519"
      "ansible_user": "root"
      "private_ip": "192.168.10.168"
    "monitoring":
      "ansible_host": "139.100.219.28"
      "ansible_ssh_private_key_file": "~/.ssh/id_ed25519"
      "ansible_user": "root"
      "private_ip": "192.168.10.239"
