name: Build and Push Docker Images

on:
  push:
    branches: ["merge/main-and-docker-setup"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "ReDaX7355" --password-stdin

      - name: Build backend image
        run: |
          OWNER_LC=$( echo GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          docker build \
          --build_arg DATABASE_URL=${{ secrets.DATABASE_URL}} \
          --build_arg PORT=${{ secrets.PORT_BACKEND}} \
          -t ghcr.io/$OWNER_LC/backend:latest ./backend
          docker push ghcr.io/$OWNER_LC/backend:latest

      - name: Build frontend image
        run: |
          OWNER_LC=$( echo GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          --build_arg DATABASE_URL=${{ secrets.DATABASE_URL}} \
          --build_arg PORT=${{ secrets.PORT_BACKEND}} \
          docker build -t ghcr.io/$OWNER_LC/frontend:latest ./frontend
          docker push ghcr.io/$OWNER_LC/frontend:latest
