name: Build and Push Docker Images

on:
  push:
    branches: ["merge/main-and-docker-setup"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "ReDaX7355" --password-stdin

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER, ,}" >> $GITHUB_ENV

      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{env.OWNER_LC}}/backend:latest ./backend
          docker push ghcr.io/${{env.OWNER_LC}}/backend:latest

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{env.OWNER_LC}}/frontend:latest ./frontend
          docker push ghcr.io/${{env.OWNER_LC}}/frontend:latest
