name: Build and Push Docker Images

on:
  push:
    branches:
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js for backend
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend deps
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      - name: Install frontend deps
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test


  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "ReDaX7355" --password-stdin

      - name: Build backend image
        run: |
          OWNER_LC=$( echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          docker build \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL}} \
          --build-arg PORT=${{ secrets.PORT_BACKEND}} \
          -t ghcr.io/$OWNER_LC/backend:latest ./backend
          docker push ghcr.io/$OWNER_LC/backend:latest

      - name: Build frontend image
        run: |
          OWNER_LC=$( echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          docker build \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL}} \
          --build-arg PORT=${{ secrets.PORT_BACKEND}} \
          -t ghcr.io/$OWNER_LC/frontend:latest ./frontend
          docker push ghcr.io/$OWNER_LC/frontend:latest
